### ISSUE TITLE
PlayReady integration

### ISSUE THREAD

**Issue by wdzierzanowski** [fraunhoferfokus/open-content-decryption-module#7]
Hi,

I was wondering about OCDM and PlayReady integration. The README contains this statement,

> e2e tested with Microsoft PlayReady DRM system

But AFAICS in the OCDM and OCDMi repos, there is no code for that, and OCDMi only provides stub `IMediaKeySession` and `IMediaEngineSession` implementations. Furthermore, the communication method between OCDM and OCDMi is Linux-specific.

So my question is, what do you mean by "E2E tested"? Do you have some private IMediaKeySession, etc. implementations that talk to the PlayReady porting kit that you build on Linux? If so, do you have any plans to push those to the repo?

Thanks,
Wojtek

**Comment by mlasak** [comment]
Hi Wojtek,
With our OCDM and OCDMi repositories we show our approach of integrating an sample CDM to be substituted by your real one. Yes, in this case study we are using Chromium on Linux as described in the docs. We are open to accept more open-source adaptations (mainly glue-code) to broaden the platform and browser outreach. However, we also have non open-sourced implementations using OCDM in conjunction with PR PK with which we proof our approach. We are happy to showcase this test bed to interested parties on occasions (dedicated or related events to this topic which we are attending) or we arrange a meeting in our labs. Regarding your question, we have no plans to open-source this effort for obvious reasons at the moment. For more information on specifically PR integration please contact us directly, http://www.fokus.fraunhofer.de/fame
Best regards,
Martin
